'use client'
//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { 
  Navbar, 
  Button, 
  NavbarBrand, 
  ThemeModeScript, 
  Drawer,
  DrawerHeader,
  DrawerItems,
  Sidebar,
  SidebarItem,
  SidebarItemGroup,
  SidebarItems,
  TextInput,
  SidebarCollapse, } from 'flowbite-react';
import { useEffect, useState } from "react";
import Background from "@/components/background/background";
import { HiSearch, HiMenuAlt1 } from "react-icons/hi";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState(false);
  console.log(isOpen);
  const handleClose = () => setIsOpen(false);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Background/>
        <Navbar fluid rounded>
          <NavbarBrand href="" className="text-white bg-[#050708] hover:bg-[#050708]/90 focus:ring-4 focus:outline-none focus:ring-[#050708]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#050708]/50 dark:hover:bg-[#050708]/30 me-2 ">
            <span className="text-2xl">Benedict Polacek</span>
          </NavbarBrand>
          
          <div className="flex md:order-2">
            {/*<TextInput type="text" placeholder="Search" className="w-80"/>*/}
            <form className="max-w-md mx-auto w-100 h-13">   
              <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
              <div className="relative ">
                  <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                      <svg className="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                      </svg>
                  </div>
                  <input type="search" id="default-search" className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-900 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Interesting Posts" required />
                  <button type="submit" className="text-white absolute end-2.5 bottom-2.5 bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:ring-gray-700">Search</button>
              </div>
            </form>
            <Button onClick={() => setIsOpen(true)} color="light" className="ml-2 h-13 pl-4"><HiMenuAlt1 className="h-5 w-5 mr-2"/><div className="font-sans font-normal text-base">Popular </div></Button>
          </div>
          <Drawer open={isOpen} onClose={handleClose} position="right">
            <DrawerHeader title="Topics" titleIcon={() => <></>} />
            <DrawerItems>
              <Sidebar
                aria-label="Sidebar with multi-level dropdown example"
                className="[&>div]:bg-transparent [&>div]:p-0"
              >
                <div className="flex h-full flex-col justify-between py-2">
                  <div>
                    <form className="pb-3 md:hidden">
                      <TextInput icon={HiSearch} type="search" placeholder="Search" required size={32} />
                    </form>
                    <SidebarItems>
                      <SidebarItemGroup>
                        <SidebarCollapse label="Internet Culture (Viral)" className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="/#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Amazing</div>
                          </SidebarItem>
                          <SidebarItem href="/#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Animals & Pets</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Cringe & Facepalm</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Funny</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Interesting</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Memes</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Oddly Satisfying</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Reddit Meta</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Wholesome & Heartwarming</div>
                          </SidebarItem>
                        </SidebarCollapse>
                        <SidebarCollapse label="Games" className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Action Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Adventure Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Esports</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Gaming Consoles & Gear</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Gaming News & Discussion</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Mobile Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Other Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Role-Playing Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Simulation Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Sports & Racing Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Strategy Games</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Tabletop Games</div>
                          </SidebarItem>
                        </SidebarCollapse>
                        <SidebarCollapse label="Q&As"  className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Q&As</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Stories & Confessions</div>
                          </SidebarItem>
                        </SidebarCollapse>
                        <SidebarCollapse label="Technology" className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">3D Printing</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Artificial Intelligence & Machine Learning</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Computers and Hardware</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Consumer Electronics</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">DIY Electronics</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Programming</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Software & Apps</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Streaming Services</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Tech News & Discussion</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Virtual & Augmented Reality</div>
                          </SidebarItem>
                        </SidebarCollapse>
                        <SidebarCollapse label="Pop Culture" className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Celebrities</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Creators & Influencers</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Generations & Nostalgia</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Podcast</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Streamers</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Tarot & Astrology</div>
                          </SidebarItem>
                        </SidebarCollapse>
                        <SidebarCollapse label="Movies & TV" className="border-b-3 border-white rounded-sm">
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Action Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Animated Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Comedy Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="/crime" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Crime, Mystery, & Thriller Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Documentary Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#"  as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Drama Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Fantasy Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Horror Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Movie News & Discussion</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Reality TV</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Romance Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Sci-Fi Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">Superhero Movies & Series</div>
                          </SidebarItem>
                          <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                            <div className="max-w-48 truncate">TV News & Discussion</div>
                          </SidebarItem>
                        </SidebarCollapse>

                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Anime</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Arts</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Business</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Collectibles & Other Hobbies</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Fashion & Beauty</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Food and Drink</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Home & Garden</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Humanities & Law</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Music</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Nature & Outdoors</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">News & Politics</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Places & Travel</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Science</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Sports</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Spooky</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Vehicles</div>
                        </SidebarItem>
                        <SidebarItem href="#" as={Link} className="border-b-3 border-gray-700 rounded-sm">
                          <div className="max-w-48 truncate">Wellness</div>
                        </SidebarItem>
                      </SidebarItemGroup>
                    </SidebarItems>
                  </div>
                </div>
              </Sidebar>
            </DrawerItems>
          </Drawer>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
