import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import BackgroundSky from "@/components/background/BackgroundSky";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReduxProvider from "../lib/ReduxProvider";
import LoadingLayout from "@/components/loading/LoadingLayout";
import { ThemeModeScript } from "flowbite-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
            <head>
        <ThemeModeScript defaultMode="dark"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >

        <BackgroundSky/>
        <Header/>
        <main>      
          <Suspense fallback={<LoadingLayout />}>
            <ReduxProvider>
              {children}
            </ReduxProvider> 
          </Suspense>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
